[request]
method = "POST"
url = "http://localhost:3000/api/v2/auth/login"

[headers]
X-Vault-Token = "{{vault.test_key}}"
Content-Type = "application/json"

[body]
type = "json"
raw = """
{
  "email": "{{username}}@example.com",
  "password": "password123",
  "role": "{{role}}"
}
"""

[assert]
status = 200
json = { "token" = { "exists" = true } }
