[request]
id = "login_user"
method = "POST"
url = "http://localhost:3000/api/v2/auth/login"

[body]
raw = '{"email":"user@test.com", "password":"password", "role":"user"}'

[extract]
user_token = "json.token"
