[request]
method = "POST"
url = "http://localhost:3000/api/echo"

[body]
raw = '{"username":"{{vault.secret_user}}", "password":"{{vault.secret_pass}}"}'

[headers]
X-API-Key = "{{vault.api_key}}"

[assert]
status = 200
