[request]
id = "auth_intermediate"
method = "GET"
url = "http://localhost:3000/api/echo"

[headers]
Authorization = "Bearer {{auth_producer.token}}"

[extract]
final_key = "json.headers.authorization"
